produit:
    path:     /
    defaults: { _controller: "ProductionBundle:ParProduit:index" }

produit_show:
    path:     /{id}/show
    defaults: { _controller: "ProductionBundle:ParProduit:show" }

produit_new:
    path:     /new
    defaults: { _controller: "ProductionBundle:ParProduit:new" }

produit_create:
    path:     /create
    defaults: { _controller: "ProductionBundle:ParProduit:create" }
    methods:  POST

produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductionBundle:ParProduit:edit" }

produit_update:
    path:     /{id}/update
    defaults: { _controller: "ProductionBundle:ParProduit:update" }
    methods:  [POST, PUT]

produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductionBundle:ParProduit:delete" }
    methods:  [POST, DELETE]
