<?php

namespace Production\ProductionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OneligneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OneligneRepository extends EntityRepository
{
}
