<?php

namespace Production\ProductionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VendeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationEtapeUtilisateurRepository extends EntityRepository
{
    public function findBayclrefus($id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->Where('p.idUser =:dfr')->setParameter('dfr',$id);
        $qb->groupBy('p.idLigneBc');
        $qb->orderBy('p.id', 'DESC') ;
        return $qb->getQuery()->getResult();
    }
}
