<?php

namespace Production\ProductionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VendeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonCommandeLigneRepository extends EntityRepository
{
    public function findB($id,$cfir,$num,$produit)
    {
        $query = $this->createQueryBuilder('message')
            ->InnerJoin('message.commande', 'c')
            ->InnerJoin('c.customer', 'b')
            ->InnerJoin('message.produit', 'p');
        if(!empty($id))
              $query->andWhere('b.client like :username ')->setParameter('username', '%'.$id.'%');

        if(!empty($cfir))

              $query->andWhere('b.codeFirme like :cfir ')->setParameter('cfir', $cfir);

        if(!empty($num))

              $query ->andWhere('c.numBc = :num ')->setParameter('num', $num);

        if(!empty($produit))

            $query ->andWhere('p.titre like :produit ')->setParameter('produit', '%'.$produit.'%');
             //->andWhere('replies.user = :username')

            ;

        $sent = $query->getQuery()->getResult();
        return $sent;
    }

    public function findBayclrefus($id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->Where('p.idUser =:dfr')->setParameter('dfr',$id);
        $qb->groupBy('p.idLigneBc');
        $qb->orderBy('p.id', 'DESC') ;
        return $qb->getQuery()->getResult();
    }

}
