<?php

namespace Production\ProductionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VendeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonCommandeRepository extends EntityRepository
{
    public function findB($id,$cfir)
    {
        $query = $this->createQueryBuilder('message')
            ->InnerJoin('message.customer', 'c');

        if(!empty($id))
              $query->andWhere('c.client like :username ')->setParameter('username', '%'.$id.'%');

        if(!empty($cfir))

              $query->andWhere('message.codeFirme like :cfir ')->setParameter('cfir', $cfir);



            ;

        $sent = $query->getQuery()->getResult();
        return $sent;
    }

    public function findBayclrefus($id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->Where('p.idUser =:dfr')->setParameter('dfr',$id);
        $qb->groupBy('p.idLigneBc');
        $qb->orderBy('p.id', 'DESC') ;
        return $qb->getQuery()->getResult();
    }

}
