<?php

namespace Proxies\__CG__\Production\ProductionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BonCommandeLigne extends \Production\ProductionBundle\Entity\BonCommandeLigne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'id', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'numBc', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'commande', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'produit', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'ligneCommande', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'ligneone', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'codeProduit', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'affecter', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'montantHt', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'cloturee');
        }

        return array('__isInitialized__', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'id', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'numBc', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'commande', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'produit', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'ligneCommande', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'ligneone', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'codeProduit', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'affecter', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'montantHt', '' . "\0" . 'Production\\ProductionBundle\\Entity\\BonCommandeLigne' . "\0" . 'cloturee');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BonCommandeLigne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumBc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumBc', array());

        return parent::getNumBc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumBc($numBc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumBc', array($numBc));

        return parent::setNumBc($numBc);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeProduit', array());

        return parent::getCodeProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeProduit($codeProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeProduit', array($codeProduit));

        return parent::setCodeProduit($codeProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantHt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantHt', array());

        return parent::getMontantHt();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantHt($montantHt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantHt', array($montantHt));

        return parent::setMontantHt($montantHt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCloturee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCloturee', array());

        return parent::getCloturee();
    }

    /**
     * {@inheritDoc}
     */
    public function setCloturee($cloturee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCloturee', array($cloturee));

        return parent::setCloturee($cloturee);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommande', array());

        return parent::getCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommande($commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommande', array($commande));

        return parent::setCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduit', array());

        return parent::getProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduit($produit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduit', array($produit));

        return parent::setProduit($produit);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneCommande', array());

        return parent::getLigneCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setLigneCommande($ligneCommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLigneCommande', array($ligneCommande));

        return parent::setLigneCommande($ligneCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffecter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffecter', array());

        return parent::getAffecter();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffecter($affecter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffecter', array($affecter));

        return parent::setAffecter($affecter);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneone', array());

        return parent::getLigneone();
    }

    /**
     * {@inheritDoc}
     */
    public function setLigneone($ligneone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLigneone', array($ligneone));

        return parent::setLigneone($ligneone);
    }

}
