<?php

namespace Proxies\__CG__\Production\ProductionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WorkflowEtape extends \Production\ProductionBundle\Entity\WorkflowEtape implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'id', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'customer', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'ligneEtape', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'titre', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'description', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'idWorkflow', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'idEtapePrecedente', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'tempsPrevu');
        }

        return array('__isInitialized__', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'id', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'customer', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'ligneEtape', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'titre', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'description', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'idWorkflow', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'idEtapePrecedente', '' . "\0" . 'Production\\ProductionBundle\\Entity\\WorkflowEtape' . "\0" . 'tempsPrevu');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WorkflowEtape $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdWorkflow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdWorkflow', array());

        return parent::getIdWorkflow();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdWorkflow($idWorkflow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdWorkflow', array($idWorkflow));

        return parent::setIdWorkflow($idWorkflow);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEtapePrecedente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEtapePrecedente', array());

        return parent::getIdEtapePrecedente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEtapePrecedente($idEtapePrecedente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEtapePrecedente', array($idEtapePrecedente));

        return parent::setIdEtapePrecedente($idEtapePrecedente);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempsPrevu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempsPrevu', array());

        return parent::getTempsPrevu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempsPrevu($tempsPrevu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempsPrevu', array($tempsPrevu));

        return parent::setTempsPrevu($tempsPrevu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer($customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getLigneEtape()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLigneEtape', array());

        return parent::getLigneEtape();
    }

    /**
     * {@inheritDoc}
     */
    public function setLigneEtape($ligneEtape)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLigneEtape', array($ligneEtape));

        return parent::setLigneEtape($ligneEtape);
    }

}
