production:
    resource: "@ProductionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

ben_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /