security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_INFORMATION:      [ROLE_USER]
        ROLE_COMMERCIAL:       [ROLE_USER]
        ROLE_MARKETING:        [ROLE_USER]
        ROLE_CONTACT:          [ROLE_USER]
        ROLE_ADMIN: [ROLE_INFORMATION,ROLE_COMMERCIAL,ROLE_USER,ROLE_MARKETING,ROLE_CONTACT, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPERADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public:
            # since anonymous is allowed users will not be forced to login
            pattern:   ^/.*
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                default_target_path:  /
                remember_me: true
            remember_me:
                key:         %secret%
                lifetime: 604800
                path:     /
                domain:   ~
                user_provider: fos_userbundle
            anonymous: true
            logout:          true

        login:
            pattern:  ^/login$
            security: false
    access_control:
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, role: ROLE_USER }
