#fos userbundle
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class: Production\UserBundle\Entity\User
    from_email:
        address:        fayssal1anouar@gmail.com
        sender_name:    admin
    registration:
        confirmation:
            enabled:    true