Clients:
    type: entity
    table: clients
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        client:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        codeFirme:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: code_firme
    lifecycleCallbacks: {  }
