Liste:
    type: entity
    table: liste
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        fonction:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        societe:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        adresse:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        telephone:
            type: string
            nullable: false
            length: 13
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        site:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        message:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        forme:
            type: string
            nullable: false
            length: 12
            fixed: false
            comment: ''
        rc:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        ice:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        creation:
            type: string
            nullable: false
            length: 13
            fixed: false
            comment: ''
        effectif:
            type: string
            nullable: false
            length: 6
            fixed: false
            comment: ''
        capital:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
        object:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
        referencement:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        affichage:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        display:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
        siteconnect:
            type: string
            nullable: false
            length: 70
            fixed: false
            comment: ''
        md:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: MD
    lifecycleCallbacks: {  }
