ParProduit:
    type: entity
    table: par_produit
    uniqueConstraints:
        UNIQ_4D1AB531351E7483:
            columns:
                - id_workflow
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: Description
        idWorkflow:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_workflow
        codeProduit:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: code_produit
    lifecycleCallbacks: {  }
