Vendeur:
    type: entity
    table: vendeur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        tel:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
