Workflow:
    type: entity
    table: workflow
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
