WorkflowExecution:
    type: entity
    table: workflow_execution
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idLigneBc:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_ligne_bc
        idEtape:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_etape
        dateDebut:
            type: datetime
            nullable: true
            comment: ''
            column: date_debut
        dateFin:
            type: datetime
            nullable: true
            comment: ''
            column: date_fin
        commentaire:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        urlPj:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: url_pj
        idUtilisateur:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_utilisateur
    lifecycleCallbacks: {  }
